import "./globals.css";
import { Rubik } from "next/font/google";
import Header from "@components/header";
import Footer from "@components/footer/Footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="darktheme">
      <body
        className={`${rubik.className} flex flex-col justify-center items-center`}
      >
        <div className="w-full mx-auto max-w-min lg:max-w-6xl">
          <Header />
          <div className="pt-16 pb-16 bg-base-100 min-h-screen w-full text-center">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
